version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/Vancouver
  open-pull-requests-limit: 10
  allow:
  - dependency-name: Microsoft.AspNetCore.*
    versions:
    - 3.x
  - dependency-name: System.Net.Http.Json
    allow:
    - 3.x
