on:
  pull_request:
    branches:
      - '*'

name: Build & Test
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Dotnet Build
      run: dotnet build -c Release

    - name: Run App
      working-directory: src/BlazorApplicationInsights.Sample
      run: |
        $a = Start-Process dotnet 'run','-c','Release' -PassThru
      shell: pwsh

    - name: Install Playwright
      working-directory: src/BlazorApplicationInsights.Tests/bin/Release/netcoreapp3.1
      run: ./playwright.ps1 install
      shell: pwsh

    - name: Run Tests
      working-directory: src/BlazorApplicationInsights.Tests
      run: dotnet test -c Release