on: 
  push:
    branches: 
      - master
      - alpha
      - beta

name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Dotnet Publish
      working-directory: src/BlazorApplicationInsights.Sample
      run: dotnet publish -c Release

    - name: Deploy to Production
      if: github.ref == 'refs/heads/master'
      id: netlify
      uses: netlify/actions/cli@master
      with:
        args: deploy --prod --json -d src/BlazorApplicationInsights.Sample/bin/Release/netstandard2.1/publish/wwwroot
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

    - name: Set Test Address
      if: github.ref == 'refs/heads/master'
      run: |
        Set-Content -Path "src/BlazorApplicationInsights.Tests/BrowserTestsAddress.config" -Value "${{ steps.netlify.outputs.NETLIFY_URL }}";
      shell: pwsh

    - name: Deploy to Staging
      if: github.ref != 'refs/heads/master'
      id: netlify2
      uses: netlify/actions/cli@master
      with:
        args: deploy --json -d src/BlazorApplicationInsights.Sample/bin/Release/netstandard2.1/publish/wwwroot
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

    - name: Set Test Address
      if: github.ref != 'refs/heads/master'
      run: |
        Set-Content -Path "src/BlazorApplicationInsights.Tests/BrowserTestsAddress.config" -Value "${{ steps.netlify2.outputs.NETLIFY_URL }}";
      shell: pwsh

    - name: Run Tests
      working-directory: src/BlazorApplicationInsights.Tests
      run: dotnet test --configuration Release

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic
      with:
        semantic_version: 17.4
        extra_plugins: |
          conventional-changelog-conventionalcommits
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Dotnet Pack 
      if: steps.semantic.outputs.new_release_published == 'true'
      working-directory: src/BlazorApplicationInsights
      run: dotnet pack -c Release -p:Version=${{ steps.semantic.outputs.new_release_version }}

    - name: Dotnet Nuget Push
      if: steps.semantic.outputs.new_release_published == 'true'
      working-directory: src/BlazorApplicationInsights/bin/Release
      run: dotnet nuget push BlazorApplicationInsights.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
